version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: codedeploy/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: codedeploy/post_install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: codedeploy/run.sh
      timeout: 120
      runas: ubuntu
  ApplicationStop:
    - location: codedeploy/stop.sh
      timeout: 120
      runas: ubuntu
  ValidateService:
    - location: codedeploy/validate.sh
      timeout: 60
      runas: ubuntu
