jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: circleci/mysql:5.7.30
        environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: assignment
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:latest
      - image: circleci/mysql:5.7.30
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: assignment
    steps:
      - checkout      
      - run:
          command: |
            sudo apt-get install python-setuptools
            sudo easy_install pip
            sudo pip install awscli
          name: Install AWS Cli
      - run:
          command: aws configure set region $AWS_DEFAULT_REGION
          name: AWS default region
      - run:
          command: sudo apt update -y && sudo apt-get install zip unzip -y
          name: Install Zip
      - run:
          command: zip -9 --exclude '*.git*' -r csye-6225-bookstore-$CIRCLE_BUILD_NUM.zip .
          name: Create Zip before node_modules take over
      - run:
          command: mkdir codedeploy_artifact && mv csye-6225-bookstore-$CIRCLE_BUILD_NUM.zip codedeploy_artifact/
          name: move zip file to new dir
      - run:
          command: npm install && npm test
          name: Install packages and run tests
      - run:
          command: aws s3 cp codedeploy_artifact/csye-6225-bookstore-$CIRCLE_BUILD_NUM.zip s3://codedeploy.$DEPLOY_ENV.kinnarkansara.me/csye-6225-bookstore-$CIRCLE_BUILD_NUM.zip
          name: Push artifact to s3 bucket
workflows:
  version: 2
  pr-check:
    jobs:
      - test
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
