jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: npm install && npm test
workflows:
  version: 2
  pr-check:
    jobs:
      - build
      - test
