jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: circleci/mysql:5.7.30
        environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: assignment
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:latest
      - image: circleci/mysql:5.7.30
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: assignment
    steps:
      - checkout
      - run: npm install && npm test
workflows:
  version: 2
  pr-check:
    jobs:
      - build
      - test
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - test:
          filters:
            branches:
              only:
                - master
